branches:
  only:
    - master
    - travis-ci

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"

matrix:
  include:
    - language: node_js
      node_js:
        - "8"
      cache:
        yarn: true
      script: ./scripts/ci_node.sh

    - os: osx
      language: objective-c
      xcode_project: ios/SpaceViewer.xcworkspace
      xcode_scheme: SpaceViewer
      osx_image: xcode11.1
      env:
        - JOB_NAME=IOS
      before_install:
        - yarn
        - cd ios; pod install
      script: ./scripts/ci_deploy_ios.sh
