name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Use specific Java version for sdkmanager to work
      uses: joschi/setup-jdk@v1
      with:
        java-version: 'openjdk8'
        architecture: 'x64'

    - name: Download Android Emulator Image
      run:
        echo y | sudo $ANDROID_HOME/tools/bin/sdkmanager --verbose "system-images;android-27;google_apis;x86"

    - name: Setup emulator
      run: |
        $ANDROID_HOME/tools/bin/avdmanager create avd -n emu -k "system-images;android-27;google_apis;x86" -b "x86" -c 1G -d 7 -f

    - name: Install node_modules & Deploy
      run: |
        yarn install --frozen-lockfile
        yarn build-detox-android

    - name: Android test
      timeout-minutes: 10
      continue-on-error: true
      run: |
        export PATH=$PATH:$ANDROID_HOME/platform-tools
        $ANDROID_HOME/emulator/emulator @emu &
        adb wait-for-device; adb shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'; adb shell wm dismiss-keyguard
        yarn test-detox-android

    - uses: actions/upload-artifact@master
      with:
        name: android-failing-e2e-videos
        path: artifacts/
