name: TEST
on:
  pull_request:
    branches:
      - github-actions
jobs:
  test42:
    name: testJob
    runs-on: macOS-10.14
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - name: Install react-native cli
        run: npm install -g react-native-cli
